version: '3.7'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/.db/pgdata:/var/lib/postgresql/data
      # - ${PWD}/.db/pginitdb/:/docker-entrypoint-initdb.d
    tmpfs:
      - /tmp

  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8080:8069"
    environment:
      - HOST=db
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
